import type { GalleryToolMeta } from './types';

/** Order = display order within each group. */
export const GALLERY_TOOLS: GalleryToolMeta[] = [
  // ── Network ──────────────────────────────────────────────
  {
    id: 'sockets',
    title: 'Sockets',
    blurb: 'TCP client/server and UDP — send text or hex.',
    surface: 'agapi.net · agapi.dgram',
    status: 'live',
    accent: 'cyan',
    group: 'network',
  },
  {
    id: 'tls',
    title: 'TLS client',
    blurb: 'Secure TCP via tls.connect — SNI, optional insecure lab mode.',
    surface: 'agapi.tls',
    status: 'lab',
    accent: 'emerald',
    group: 'network',
  },
  {
    id: 'http',
    title: 'HTTP',
    blurb: 'Method, URL, headers, body → status + response.',
    surface: 'agapi.http.request',
    status: 'lab',
    accent: 'violet',
    group: 'network',
  },
  {
    id: 'http-server',
    title: 'HTTP server',
    blurb: 'Listen and reply — inspect incoming requests, set a canned response.',
    surface: 'agapi.http.createServer',
    status: 'lab',
    accent: 'blue',
    group: 'network',
  },
  {
    id: 'websocket-server',
    title: 'WebSocket server',
    blurb: 'Accept incoming WS connections, list clients, broadcast messages.',
    surface: 'agapi.http.WebSocketServer',
    status: 'lab',
    accent: 'pink',
    group: 'network',
  },
  {
    id: 'websocket-client',
    title: 'WebSocket client',
    blurb: 'Dial out to a WS server — MDN-compatible WebSocket.',
    surface: 'agapi.http.WebSocket',
    status: 'lab',
    accent: 'lime',
    group: 'network',
  },
  {
    id: 'dns',
    title: 'DNS lookup',
    blurb: 'Resolve hostnames through the OS resolver (host-backed).',
    surface: 'agapi.dns',
    status: 'lab',
    accent: 'sky',
    group: 'network',
  },
  {
    id: 'mdns',
    title: 'mDNS',
    blurb: 'Browse / advertise local services (Bonjour / DNS-SD).',
    surface: 'agapi.mdns',
    status: 'lab',
    accent: 'amber',
    group: 'network',
  },

  // ── Device ────────────────────────────────────────────────
  {
    id: 'network-status',
    title: 'Network status',
    blurb: 'Online/offline snapshot + watch, local addresses, best-effort Wi-Fi/Ethernet guess.',
    surface: 'agapi.device.getNetworkStatus',
    status: 'lab',
    accent: 'cyan',
    group: 'device',
  },
  {
    id: 'os-info',
    title: 'OS info',
    blurb: 'Platform, arch, version, hostname, locale.',
    surface: '@tauri-apps/plugin-os',
    status: 'lab',
    accent: 'rose',
    group: 'device',
  },
  {
    id: 'bluetooth',
    title: 'Bluetooth',
    blurb: 'BLE scan, connect, GATT read/write/notify — central/client role.',
    surface: 'agapi.bluetooth',
    status: 'lab',
    accent: 'indigo',
    group: 'device',
  },
  {
    id: 'sensors',
    title: 'Sensors',
    blurb: 'Accelerometer, gyroscope, attitude, heading, location.',
    surface: 'agapi.sensors (planned)',
    status: 'stub',
    accent: 'amber',
    group: 'device',
  },
  {
    id: 'haptics',
    title: 'Haptics',
    blurb: 'Impact / notification / selection feedback — mobile host, browser vibrate fallback.',
    surface: 'agapi.haptics',
    status: 'lab',
    accent: 'fuchsia',
    group: 'device',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    blurb: 'Local notifications — permission + show.',
    surface: 'agapi.notifications',
    status: 'lab',
    accent: 'sky',
    group: 'device',
  },
  {
    id: 'fs',
    title: 'Filesystem',
    blurb: 'Scoped read/write/mkdir — app data, cache, not whole-disk.',
    surface: 'agapi.fs',
    status: 'lab',
    accent: 'teal',
    group: 'device',
  },
  {
    id: 'nfc',
    title: 'NFC',
    blurb: 'NDEF scan / write — mobile-host only.',
    surface: 'agapi.nfc',
    status: 'lab',
    accent: 'violet',
    group: 'device',
  },
  {
    id: 'biometrics',
    title: 'Biometric',
    blurb: 'Face / fingerprint availability + authenticate prompt — mobile-host only.',
    surface: 'agapi.biometric',
    status: 'lab',
    accent: 'orange',
    group: 'device',
  },

  // ── Browser APIs ──────────────────────────────────────────
  {
    id: 'webrtc',
    title: 'WebRTC',
    blurb: 'Browser capability probe — media, RTCPeerConnection, data channels.',
    surface: 'browser WebRTC',
    status: 'info',
    accent: 'fuchsia',
    group: 'browser',
  },
  {
    id: 'webcodecs',
    title: 'WebCodecs',
    blurb: 'Browser encode/decode support matrix (VideoEncoder, AudioDecoder, …).',
    surface: 'browser WebCodecs',
    status: 'info',
    accent: 'teal',
    group: 'browser',
  },
  {
    id: 'crypto',
    title: 'Crypto',
    blurb: 'Browser Web Crypto — random, hash, HMAC, AES-GCM, PBKDF2 (not agapi.crypto).',
    surface: 'crypto.subtle · getRandomValues',
    status: 'lab',
    accent: 'orange',
    group: 'browser',
  },
  {
    id: 'web-animations',
    title: 'Web Animations',
    blurb: '14 live examples — smart-home controls plus card/list/gallery patterns (FLIP reorder, lightbox, carousel, skeleton reveal).',
    surface: 'Web Animations API (Element.animate)',
    status: 'lab',
    accent: 'pink',
    group: 'browser',
  },
  {
    id: 'gestures',
    title: 'Gestures',
    blurb: "cf-runtime's hand-rolled tap/pan/press/swipe, ported from Pixi to a Touch Events canvas — plus real multitouch pinch/rotate.",
    surface: 'Touch Events API (no gesture library)',
    status: 'lab',
    accent: 'lime',
    group: 'browser',
  },

  // ── Drivers ───────────────────────────────────────────────
  {
    id: 'matter',
    title: 'Matter',
    blurb: 'Real device discovery (mDNS) + commissioning (PASE/CASE) via matter.js, on top of agapi.dgram/agapi.device.',
    surface: '@agapi/matterjs · @project-chip/matter.js',
    status: 'lab',
    accent: 'violet',
    group: 'drivers',
  },
  {
    id: 'sonos',
    title: 'Sonos',
    blurb: 'Discover speakers via SSDP, then play/pause/volume/mute over UPnP SOAP — real devices on your LAN.',
    surface: '@agapi/sonos · agapi.dgram + agapi.http',
    status: 'lab',
    accent: 'emerald',
    group: 'drivers',
  },
  {
    id: 'simple-device',
    title: 'SimpleDevice',
    blurb: 'Copy-paste TCP/line driver skeleton — power on|off|? over CRLF, agapi.net + node:net + mock server.',
    surface: '@agapi/driver-template · agapi.net',
    status: 'lab',
    accent: 'cyan',
    group: 'drivers',
  },

  // ── Examples ──────────────────────────────────────────────
  {
    id: 'webrtc-p2p',
    title: 'WebRTC P2P (LAN)',
    blurb: 'Serverless peer-to-peer over the local network — mDNS discovery + local WebSocket signaling, no STUN/TURN, no cloud.',
    surface: 'RTCPeerConnection + agapi.mdns + agapi.http.WebSocketServer/WebSocket',
    status: 'lab',
    accent: 'fuchsia',
    group: 'examples',
  },
];
