import type { GalleryToolMeta } from './types';

/** Order = gallery display order / roadmap sequence. */
export const GALLERY_TOOLS: GalleryToolMeta[] = [
  {
    id: 'sockets',
    title: 'Sockets (NC)',
    blurb: 'Netcat-style TCP client/server and UDP — send text or hex.',
    surface: 'agapi.net · agapi.dgram',
    status: 'live',
    accent: 'cyan',
  },
  {
    id: 'tls',
    title: 'TLS client',
    blurb: 'Secure TCP via tls.connect — SNI, optional insecure lab mode.',
    surface: 'agapi.tls',
    status: 'lab',
    accent: 'emerald',
  },
  {
    id: 'http',
    title: 'HTTP',
    blurb: 'Method, URL, headers, body → status + response.',
    surface: 'agapi.http.request',
    status: 'lab',
    accent: 'violet',
  },
  {
    id: 'http-server',
    title: 'HTTP server',
    blurb: 'Listen and reply — inspect incoming requests, set a canned response.',
    surface: 'agapi.http.createServer',
    status: 'lab',
    accent: 'blue',
  },
  {
    id: 'websocket-server',
    title: 'WebSocket server',
    blurb: 'Accept incoming WS connections, list clients, broadcast messages.',
    surface: 'agapi.http.WebSocketServer',
    status: 'lab',
    accent: 'pink',
  },
  {
    id: 'websocket-client',
    title: 'WebSocket client',
    blurb: 'Dial out to a WS server — MDN-compatible WebSocket.',
    surface: 'agapi.http.WebSocket',
    status: 'lab',
    accent: 'lime',
  },
  {
    id: 'dns',
    title: 'DNS lookup',
    blurb: 'Resolve hostnames through the OS resolver (host-backed).',
    surface: 'agapi.dns',
    status: 'lab',
    accent: 'sky',
  },
  {
    id: 'mdns',
    title: 'mDNS',
    blurb: 'Browse / advertise local services (Bonjour / DNS-SD).',
    surface: 'agapi.mdns',
    status: 'lab',
    accent: 'amber',
  },
  {
    id: 'crypto',
    title: 'Crypto',
    blurb: 'Browser Web Crypto — random, hash, HMAC, AES-GCM, PBKDF2 (not agapi.crypto).',
    surface: 'crypto.subtle · getRandomValues',
    status: 'lab',
    accent: 'orange',
  },
  {
    id: 'camera',
    title: 'Camera',
    blurb: 'Mobile / host camera capture for panels and diagnostics.',
    surface: 'host mobile API (planned)',
    status: 'stub',
    accent: 'rose',
  },
  {
    id: 'bluetooth',
    title: 'Bluetooth',
    blurb: 'BLE / classic hooks for device pairing and control.',
    surface: 'host mobile API (planned)',
    status: 'stub',
    accent: 'indigo',
  },
  {
    id: 'webrtc',
    title: 'WebRTC',
    blurb: 'Browser capability probe — media, RTCPeerConnection, data channels.',
    surface: 'browser WebRTC',
    status: 'info',
    accent: 'fuchsia',
  },
  {
    id: 'webcodecs',
    title: 'WebCodecs',
    blurb: 'Browser encode/decode support matrix (VideoEncoder, AudioDecoder, …).',
    surface: 'browser WebCodecs',
    status: 'info',
    accent: 'teal',
  },
];
